name: movie_colony
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.1
  connectivity_plus: ^1.0.3
  cupertino_icons: ^1.0.3
  dartz: ^0.9.2
  equatable: ^2.0.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.1
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  google_sign_in: ^5.1.0
  hooks_riverpod: ^1.0.1
  http: ^0.13.3
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  mockito: ^5.0.7
  shared_preferences: ^2.0.7

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator:
  json_serializable: ^4.1.2
  very_good_analysis: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR-Regular
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
